### DISCUSSION TITLE
Identify the best solutions for CI/CD and builds

### DISCUSSION THREAD

**Discussion by girodav** [elastic/assetbeat#31] [General]
(This discussion serves as a placeholder to consolidate any discussion around what to use as CI/CD and build tool for this repo)

# CI

## Requirements
- Ease of use
- Needs to be compatible with the build tool of choice
- Whatever runs on the CI needs to be reproducible locally / in a dev env. No need to do "trial and error" on PRs to figure out if the CI would pass

## Possible alternatives
- BuildKite
- Github Actions
- ?

# Build tool

## Requirements
- Ease of use
- Should be multi-platform (Windows, macos, linux...)
- Needs to work with the CI of choice

## Alternatives
- Magefiles
- [Taskfile](https://taskfile.dev/)
- Makefiles
- ?

**Comment by girodav** [comment]
I am doing some tests with Taskfile on https://github.com/girodav/inputrunner/tree/taskfile , if anyone wants to have a look.
From my initial tests, I find it much easier to use than Magefiles. With 0 knowledge of it, I managed to replicate the current magefile in few mins. I also personally find it clearer to read than Magefiles.

Example:

```
version: '3'

tasks:
  go:mod:download:
    cmds:
      - go mod download
  go:build:
    cmds:
      - go build -v .
  go:test:
    cmds:
      - go test ./... -coverprofile=coverage.out
  go:tool:coverage:
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
  staticcheck:
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - staticcheck -f=stylish ./...
  gosec:
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - gosec ./...

  build:
    desc: Build the project
    deps:
      - task: go:build
      - task: go:mod:download
  test:
    desc: Run tests and produce a coverage report
    deps:
      - task: go:tool:coverage
      - task: go:test
  check:
    desc: Run a static analysis check and look for any security vulnerabilities
    deps: [gosec, staticcheck]
```

It can be integrated in Github actions very easily with https://github.com/arduino/setup-task
