### ISSUE TITLE
Make index namespace user-configurable

### ISSUE THREAD

**Issue by girodav** [elastic/assetbeat#141]
While index type and dataset should not be user-configurable for assets, we should enable users to define their own index namespace.
Proposed field:
```
inputrunner.inputs:
  - type: assets_type
    [...other fields...]
    index_namespace: "mynamespace"
```
