### ISSUE TITLE
[GCP] Define what to use as `asset.id`

### ISSUE THREAD

**Issue by girodav** [elastic/assetbeat#226]
## Context

Each GCP resource has two fields that can be considered as a form of ID:

- `id`, e.g. `664330941630801504`
- `selfLink`, e.g. `https://www.googleapis.com/compute/v1/projects/elastic-obs-integrations-dev/zones/us-central1-a/instances/instance-1`

We currently use `id` as `asset.id` for all the resources we collect. However, it poses some challenges when trying to link assets through parent/child relationships.

## The issue

Using `id` as `asset.id` has two main issues:

- It is unclear how unique it is. I could not find any documentation about it.
- When listing associated resources (e.g VPC network a compute instance is running in), GCP generally lists the related Resource URI (i.e its selfLink), not its `id`.

Example (see `network` and `subnetwork`):
```
networkInterfaces:
- accessConfigs:
  - kind: compute#accessConfig
    name: External NAT
    networkTier: PREMIUM
    type: ONE_TO_ONE_NAT
  fingerprint: 111111111111
  kind: compute#networkInterface
  name: nic0
  network: https://www.googleapis.com/compute/v1/projects/elastic-obs-integrations-dev/global/networks/default
  networkIP: 10.128.15.204
  stackType: IPV4_ONLY
  subnetwork: https://www.googleapis.com/compute/v1/projects/elastic-obs-integrations-dev/regions/us-central1/subnetworks/default
```
This implies that every time we need to collect an asset and populate either `asset.parents` or `asset.children`, we need to make a "describe" API call on each parent/child, to find their `id`.

- The official Google Cloud doc only mentions the URI https://cloud.google.com/apis/design/resource_names

## Proposal

I propose to use a SHA384 hash of `selfLink` as `asset.id`. This solution has the following pros and cons:
* Pros
  - `selfLink` is already used as unique identifier within Google Cloud APIs, so `asset.id` is guaranteed to be unique, as far as the pool of possible outputs of the hashing algorithm we choose is "big" enough ([some math about this](https://en.wikipedia.org/wiki/Birthday_attack#Mathematics)).
  - It won't require additional describe API calls.
* Cons
  - `selfLink` is not explicitly published by GCP integrations/beats modules. The implicit collector would need to compose it from the available information (project ID, region, etc).
  - GCP integrations/beats modules publishes `id` as `host.id`.
